@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.moreRenewableFlora.mixin;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;